name: Atualizar Relatorios CLIF

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Esta ação instala o Chrome e o Driver compatível automaticamente
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Instalar Dependencias
        run: |
          pip install pandas gspread oauth2client selenium==4.10.0 openpyxl

      - name: Rodar Script do Thiago
        run: python robo_mestre.py
        env:
          USUARIO: ${{ secrets.USUARIO_CLIF }}
          SENHA: ${{ secrets.SENHA_CLIF }}
          GOOGLE_CHAVE_JSON: ${{ secrets.GOOGLE_CHAVE }}
