name: Atualizar Relatorios CLIF

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: |
          pip install pandas gspread oauth2client selenium==4.10.0 openpyxl webdriver-manager functions-framework

      - name: Rodar Script do Thiago
        run: python main.py
        env:
          USUARIO: ${{ secrets.USUARIO_CLIF }}
          SENHA: ${{ secrets.SENHA_CLIF }}
          GOOGLE_CHAVE_JSON: ${{ secrets.GOOGLE_CHAVE }}
          
      - name: Upload da Foto de Erro
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: visao-do-robo
          path: "*.png"
